### ISSUE TITLE
bug:  npm2yarn2pnpm not working with docusaurus@2.0.0-beta.21

### ISSUE THREAD

**Issue by ndom91** [sapphiredev/documentation-plugins#75] opened 2022-07-01 18:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

The meta tag `npm2yarn2pnpm` has no affect on bash code blocks. Where I'd previously used `npm2yarn`, I've installed `@sapphire/docusaurus-plugin-npm2yarn2pnpm` and added:

```
  ```bash npm2yarn2pnpm
  npm install react
  ` ``
```

However, this has no affect, and the codeblock is printed as a normal bash syntaxhighlighted codeblock.

### Steps To Reproduce

1. Install `@sapphire/docusaurus-plugin-npm2yarn2pnpm`
2. Add to your `docusaurus.config.js`
```
remarkPlugins: [ 
  require("@sapphire/docusaurus-plugin-npm2yarn2pnpm"),
]
```
3. Add to your docs files (i.e. `index.md`)
```
  ```bash npm2yarn2pnpm
  npm install react
  ` ``
```

Watch it get rendered as such:

![image](https://user-images.githubusercontent.com/7415984/176954242-786f4018-f451-4a0e-861e-6a36ad4ed1f4.png)

### Expected behavior

Expect `npm`, `yarn`, and `pnpm` tab component to be rendered

### Screenshots

![image](https://user-images.githubusercontent.com/7415984/176954272-e6c2d2d3-f1d5-42aa-8e6c-b08673d16a13.png)

### Additional context

See for example, this draft PR in my docusaurus project:

1. Preview Deploy: https://next-auth-2caln0sb0-nextauthjs.vercel.app/getting-started/upgrade-v4
  1a. The very first bash codeblock on this page, `npm install next-auth`, is supposed to be rendered with the various package manager tabs. But as you can see, it is not.
3. PR: https://github.com/nextauthjs/next-auth/pull/4805

**Comment by vladfrangu** [comment] 2022-07-01 21:35
This isn't a bug per say, check how we're doing it on our website:

https://github.com/sapphiredev/website/blob/main/docusaurus.config.js#L3

https://github.com/sapphiredev/website/blob/main/docusaurus.config.js#L184

You'll need to destructure the method itself. Can you try that and followup if that fixes it or not? 🙏

**Comment by favna** [comment] 2022-07-02 09:12
Adding to that, the difference with the other plugin comes from how we export the plugin. Whereas the npm2yarn plugin uses `export =` with a note:
> To continue supporting `require('npm2yarn')` without the `.default` ㄟ(▔,▔)ㄏ

Because we're not limited to a specific setup like docusaurus is we opted to just embrace the modern exports.

**Comment by ndom91** [comment] 2022-07-03 11:17
@vladfrangu ah thank you for the tip! Had to be a named import. 

Working now!

**Comment by vladfrangu** [comment] 2022-07-03 11:43
Glad to hear it worked! I'll be closing this issue then as it's not a bug, but followup if there's any other issues!

**Closed by vladfrangu** 2022-07-03 11:43 UTC
Labels: Bug: Unverified
